version: '3.8'

volumes:
  data-es:


services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  chatbot-server:
    build: .
    environment:
      - ES_HOSTS=elasticsearch
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

  blenderbot:
    # command: python parlai/scripts/interactive_web.py --task blended_skill_talk  --host 0.0.0.0 -mf zoo:sea/bart_fid_sqse/model --search-server http://chatbot-server:5000/search
    build: blenderbot
    environment:
      - SCRIPT=scripts/interactive_web.py
      - TASK=blended_skill_talk
      - MODEL=zoo:blenderbot2/blenderbot2_400M/model
    stdin_open: true
    tty: true
    depends_on:
      - chatbot-server
    volumes:
      - ./data:/opt/ParlAI/data:rw
      - ./scripts:/opt/ParlAI/scripts:ro
    ports:
      - 8080:8080
